on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      sha:
        required: true
        type: string
      part:
        required: true
        type: string
      new_tag:
        required: true
        type: string
jobs:
  # https://github.com/peter-evans/create-pull-request
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ATTRIBUTE_PUBLISHER_GITHUB_ACTIONS_TOKEN }}
          repository: tommyjxl/gha-workflow

      - name: Build
        run: echo ${{ inputs.new_tag }} > ReleaseTag.txt

      - name: Test
        run: cat ReleaseTag.txt

      - name: Bump deployment version
        run: date +%s > report.txt

      - name: Format Tag
        id: format_tag
        run: |
          tag="${{ inputs.new_tag }}"
          formatted_tag="${tag//.}"
          echo "Formatted tag: $formatted_tag"
          echo "formatted_tag=$formatted_tag" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ATTRIBUTE_PUBLISHER_GITHUB_ACTIONS_TOKEN }}
          commit-message: bump deployment version
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: release-${{ steps.format_tag.outputs.formatted_tag }}-${{ github.actor }}-${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          delete-branch: true
          title: 'Deployment requested by Attribute Publisher: GitHub Release ${{ inputs.part }} version bumped to ${{ inputs.new_tag }}'
          body: |
            Deployment requested by [Attribute Publisher](https://github.com/deliveryhero/data-cdp-attribs-conf)
            
            - Release Info
              - GitHub release ${{ inputs.part }} version bumped to: ${{ inputs.new_tag }}
              - What's changed: https://github.com/deliveryhero/data-cdp-attribs-conf/releases/tag/${{ inputs.new_tag }}

            - Debug Info
              - GitHub Action Run: https://github.com/deliveryhero/data-cdp-attribs-conf/actions/runs/${{ github.run_id }}  
              - Run Number: ${{ github.run_number }}
              - Run Attempt: ${{ github.run_attempt }}

          labels: |
            automated
            attribute_publisher
          # assignees: tommyjxl
          # reviewers: tommyjxl
          # team-reviewers: |
          #   developers
          #   qa-team
          draft: false
