name: Push Release Notes

# on:
#   workflow_run:
#     workflows: ["Tag"]
#     types:
#       - completed

# on:
#   push:
#     tags:
#       - "**"

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}  # checkout the same code from prior workflow

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Test
        run: cat Release.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            README.md
            LICENSE

      - name: Trigger deploy PR workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: ${{ github.repository }}
          event-type: trigger-deploy-pr-workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
