name: Push Release Notes

# on:
#   workflow_run:
#     workflows: ["Tag"]
#     types:
#       - completed

# on:
#   push:
#     tags:
#       - "**"

# on:
#   push:
#     tags:
#       - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}  # checkout the same code from prior workflow

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Test
        run: cat Release.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_and_push_tag.outputs.new_tag }}
          generate_release_notes: true

