name: Push Release Notes

on:
  repository_dispatch:
    types: [trigger-release-workflow]
  push:
    tags:
      - "**"

# on:
#   workflow_run:
#     workflows: ["Tag"]
#     types:
#       - completed

# on:
#   push:
#     tags:
#       - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}  # checkout the same code from prior workflow

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Test
        run: cat Release.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.ATTRIBUTE_PUBLISHER_GITHUB_ACTIONS_TOKEN }}
          tag_name: ${{ github.event.client_payload.new_tag }}
          generate_release_notes: true

      - name: Trigger deployment PR workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ATTRIBUTE_PUBLISHER_GITHUB_ACTIONS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-deployment-pr-workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "part": "${{ github.event.client_payload.part }}", "new_tag": "${{ github.event.client_payload.new_tag }}"}'
