name: Push Release Notes

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      sha:
        required: true
        type: string
      part:
        required: true
        type: string
      new_tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}  # checkout the same code from prior workflow

      - name: Build
        run: echo ${{ inputs.sha }} > Release.txt

      - name: Test
        run: cat Release.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.ATTRIBUTE_PUBLISHER_GITHUB_ACTIONS_TOKEN }}
          tag_name: ${{ inputs.new_tag }}
          generate_release_notes: true

  push-deployment-pr:
    uses: tommyjxl/gha-sandbox/.github/workflows/deployment-pr.yaml@tag-and-release
    needs: [ build ]
    if: contains(needs.*.result, 'success')
    with:
      ref: ${{ github.ref }}
      sha: ${{ github.sha }}
      part: ${{ steps.bump_and_push_tag.outputs.part }}
      new_tag: ${{ steps.bump_and_push_tag.outputs.new_tag }}
