# https://github.com/anothrNick/github-tag-action
name: Tag
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      id: bump_and_push_tag
      uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true
        PRERELEASE_SUFFIX: null
        DRY_RUN: false

    - name: Build
      run: echo ${{ github.sha }} > Tag.txt

    - name: Test
      run: cat Tag.txt

    - name: Trigger GitHub Release
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.API_TOKEN_GITHUB }}
        repository: ${{ github.repository }}
        event-type: trigger-release-workflow
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "tag": "${{ steps.bump_and_push_tag.outputs.tag }}", "new_tag": "${{ steps.bump_and_push_tag.outputs.new_tag }}"}'
