# https://github.com/anothrNick/github-tag-action
name: Tag
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      id: bump_and_push_tag
      uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.ATTRIBUTE_PUBLISHER_GITHUB_ACTIONS_TOKEN }}
        WITH_V: true
        PRERELEASE_SUFFIX: null
        DRY_RUN: false

    - name: Build
      run: echo ${{ github.sha }} > Tag.txt

    - name: Test
      run: cat Tag.txt

  push-release:
    uses: tommyjxl/gha-sandbox/.github/workflows/release.yaml@tag-and-release
    needs: [ build ]
    if: contains(needs.*.result, 'success')
    with:
      ref: ${{ github.ref }}
      sha: ${{ github.sha }}
      part: ${{ build.steps.bump_and_push_tag.outputs.part }}
      new_tag: ${{ build.steps.bump_and_push_tag.outputs.new_tag }}
